// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6F_IWDz4d1Nb8vqVO7WCILyaNt_IQqNc',
    appId: '1:743322508663:web:e4ac734e25a7fd572cd572',
    messagingSenderId: '743322508663',
    projectId: 'app-transprogreso-choco',
    authDomain: 'app-transprogreso-choco.firebaseapp.com',
    storageBucket: 'app-transprogreso-choco.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIImGupJPZBHbOlgUIYZAbMBIEZ09ukGE',
    appId: '1:743322508663:android:b4311e1074bd80412cd572',
    messagingSenderId: '743322508663',
    projectId: 'app-transprogreso-choco',
    storageBucket: 'app-transprogreso-choco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdb7NCdh2X6bnIbYrcLMb8Vy094cuwrA',
    appId: '1:743322508663:ios:531401d081de1c662cd572',
    messagingSenderId: '743322508663',
    projectId: 'app-transprogreso-choco',
    storageBucket: 'app-transprogreso-choco.appspot.com',
    iosBundleId: 'com.transprogresochoco.appTransprogresochoco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdb7NCdh2X6bnIbYrcLMb8Vy094cuwrA',
    appId: '1:743322508663:ios:e3911165d76404b72cd572',
    messagingSenderId: '743322508663',
    projectId: 'app-transprogreso-choco',
    storageBucket: 'app-transprogreso-choco.appspot.com',
    iosBundleId: 'com.transprogresochoco.appTransprogresochoco.RunnerTests',
  );
}
